# Generated by Django 2.0 on 2018-05-13 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='discussions',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='discussions',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 11, 23, 49, 989374)),
        ),
        migrations.AddField(
            model_name='replies',
            name='replied_to',
            field=models.ManyToManyField(to='portals.Discussions'),
        ),
    ]
