# Generated by Django 2.0 on 2018-05-18 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='voted_by',
        ),
        migrations.AlterField(
            model_name='discussions',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 22, 45, 55, 11318)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 22, 45, 55, 11318)),
        ),
    ]
