# Generated by Django 2.0 on 2018-05-18 17:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0002_auto_20180518_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='voted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussions',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 22, 46, 46, 118976)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 22, 46, 46, 118976)),
        ),
    ]
