# Generated by Django 2.0 on 2018-05-13 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20180513_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 12, 5, 50, 777536)),
        ),
        migrations.AlterField(
            model_name='discussions',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 12, 5, 50, 763499)),
        ),
    ]
