# Generated by Django 2.0 on 2018-05-18 17:21

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0003_auto_20180518_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussions',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 22, 51, 48, 337556)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 22, 51, 48, 337556)),
        ),
        migrations.RemoveField(
            model_name='replies',
            name='voted_by',
        ),
        migrations.AddField(
            model_name='replies',
            name='voted_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
